# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QrWgsAO8cmHjfbBvG6vbyYshwDNOc2c
"""

!pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread( "download.jpg")
cv2_imshow(rasm)

qoraoq= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(qoraoq)

!pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread( "download1.jpg")
cv2_imshow(rasm)

qoraoq= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(qoraoq)

!pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread( "download2.jpg")
cv2_imshow(rasm)

qoraoq= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(qoraoq)